{
 "title": "HP SNMP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Host", "query": { "query": "label_values(disk_health,ip)" } }
  ]
 },
 "panels": [
  { "title": "Power Supply", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power Supply",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "power_supply{ip=\"$Host\"}",
     "legendFormat": "{{slot}} {{ip}}"
    }
   ]
  },
  { "title": "Raid Condition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Raid Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raid_status{ip=\"$Host\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Disk State",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_health{ip=\"$Host\"}",
     "legendFormat": "{{slot}} {{ip}}"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_temperature{ip=\"$Host\"}",
     "legendFormat": "{{slot}} {{ip}}"
    }
   ]
  },
  {
   "title": "Disk Smart Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_health_smart{ip=\"$Host\"}",
     "legendFormat": "{{slot}} {{ip}}"
    }
   ]
  }
 ]
}